/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconTablerArrowBarDown: typeof import('~icons/tabler/arrow-bar-down.jsx').default
  const IconTablerArrowBarRight: typeof import('~icons/tabler/arrow-bar-right.jsx').default
  const IconTablerArrowsHorizontal: typeof import('~icons/tabler/arrows-horizontal.jsx').default
  const IconTablerCode: typeof import('~icons/tabler/code.jsx').default
  const IconTablerDirectionArrows: typeof import('~icons/tabler/direction-arrows.jsx').default
  const IconTablerEye: typeof import('~icons/tabler/eye.jsx').default
  const IconTablerLock: typeof import('~icons/tabler/lock.jsx').default
  const IconTablerLockOpen: typeof import('~icons/tabler/lock-open.jsx').default
  const IconTablerMoodAnnoyed: typeof import('~icons/tabler/mood-annoyed.jsx').default
  const IconTablerMoodEdit: typeof import('~icons/tabler/mood-edit.jsx').default
  const IconTablerMoodEmpty: typeof import('~icons/tabler/mood-empty.jsx').default
  const IconTablerMoodNeutral: typeof import('~icons/tabler/mood-neutral.jsx').default
  const IconTablerMoodSad: typeof import('~icons/tabler/mood-sad.jsx').default
  const IconTablerMoodSmile: typeof import('~icons/tabler/mood-smile.jsx').default
  const IconTablerMoodUnamused: typeof import('~icons/tabler/mood-unamused.jsx').default
  const IconTablerMoodWink2: typeof import('~icons/tabler/mood-wink2.jsx').default
  const IconTablerPencil: typeof import('~icons/tabler/pencil.jsx').default
  const IconTablerRefresh: typeof import('~icons/tabler/refresh.jsx').default
  const IconTablerSettings: typeof import('~icons/tabler/settings.jsx').default
  const IconTablerShredder: typeof import('~icons/tabler/shredder.jsx').default
}
